apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2020-04-25T15:53:56Z'
  labels:
    app: business-content-service
  name: business-content-service
  namespace: eol-dev
  resourceVersion: '657959722'
  selfLink: /api/v1/namespaces/eol-dev/services/business-content-service
  uid: f88e379f-870c-11ea-a42c-0601fd422288
spec:
  clusterIP: 172.30.49.235
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: business-content-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
