apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2020-04-24T09:27:21Z'
  labels:
    app: grafana
  name: grafana
  namespace: eol-dev
  resourceVersion: '656786855'
  selfLink: /api/v1/namespaces/eol-dev/services/grafana
  uid: ccc1b5af-860d-11ea-9f16-068b91999b6e
spec:
  clusterIP: 172.30.175.200
  ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    deploymentconfig: grafana
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
